apiVersion: apps/v1
kind: Deployment
metadata:
  name: meowapp-deployment
  labels:
    app: meowapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: meowapp
  template:
    metadata:
      labels:
        app: meowapp
    spec:
      containers:
      - name: meowapp
        image: gcr.io/the-gay-agenda-69/meowapp:v0.0.1
        ports:
        - containerPort: 8888

